# Generated by Django 5.0.1 on 2024-01-10 09:29

import countgame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('playernr', countgame.models.MySmallIntegerField(validators=[countgame.models.MySmallIntegerField.validate_range])),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
