# Generated by Django 5.0.1 on 2024-01-11 19:54

import countgame.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countgame', '0003_alter_game_playernr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='playernr',
            field=countgame.models.MySmallIntegerField(validators=[countgame.models.MySmallIntegerField.validate_range]),
        ),
    ]
