# Generated by Django 5.0.1 on 2024-01-28 20:57

import countgame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countgame', '0006_test_remove_game_playernr_game_playersnr_game_testg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='TEXT',
        ),
        migrations.RemoveField(
            model_name='test',
            name='TEXT1',
        ),
        migrations.AddField(
            model_name='test',
            name='dynamic_field',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='playersnr',
            field=countgame.models.MySmallIntegerField(default=0, validators=[countgame.models.MySmallIntegerField.validate_range]),
        ),
    ]
